{
    'name': 'Inventory Requisition',
    'version': '18.0.1.0.0',
    'category': 'Inventory',
    'summary': 'Manage inventory requisition of employees',
    'description': """Create inventory requisition requests with multi-level approvals 
    from department head and inventory manager. Generate PDF reports for each requisition.""",
    'company': 'Courage Gumbero',
    'maintainer': 'Geenet',
    'website': 'https://geenet.co.zw',
    'depends': ['base', 'hr', 'stock','sale_management'],
    'data': [
        'security/inventory_requisition_groups.xml',
        'security/inventory_requisition_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/inventory_requisition_views.xml',
        'views/requisition_order_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_department_views.xml',
        'report/inventory_requisition_templates.xml',
        'report/inventory_requisition_report.xml',
    ],
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}